### Create Customer (Debug)

POST http://localhost:8090/api/customers
Accept: application/json
Content-Type: application/json

{
  "address": "Jakarta",
  "email": "customer6@gmail.com",
  "phoneNumber": "4254353534"
}

### Get Customer
GET http://localhost:8090/api/customers
Accept: application/json


### Update Customer
PUT http://localhost:8090/api/customers/264
Accept: application/json
Content-Type: application/json

{
  "address": "Bandung"
}

### Delete Customer
DELETE http://localhost:8090/api/customers/264
Accept: application/json


### Create Account
POST http://localhost:8090/api/customers/266/accounts
Accept: application/json
Content-Type: application/json

{
  "accountNumber": "2342342",
  "accountName": "Saving Account",
  "accountType": "Saving",
  "accountBalance": 13131.92
}


### Get Account
GET http://localhost:8090/api/customers/266/accounts
Accept: application/json

### Update Account
PUT http://localhost:8090/api/customers/266/accounts/2342342
Accept: application/json
Content-Type: application/json

{
  "accountBalance": 99999.92
}

### Delete Account
DELETE http://localhost:8090/api/customers/266/accounts/2342342
Accept: application/json